version: '3'

services:
  v-keycloak:
    image: quay.io/keycloak/keycloak:12.0.1
    container_name: v-keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin