version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
    image: postgres
    container_name: v-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:12.0.1
    container_name: v-keycloak
    #volumes:
    #  - ./imports:/opt/jboss/keycloak/imports
    # todo import directly from file! for that don't leak secrets
    ports:
      - 8080:8080
      - 587:587
    depends_on:
      - postgres
    environment:
      # KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
      # todo import directly from file! for that don't leak secrets
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password